### PR TITLE
Development of basic framework

### PR DESCRIPTION
**Pull request by krober10nd**

### CODE REVIEW

**Comment by zcobell** [comment]
Looks like some of the binary pyc files got sucked in by mistake

**Comment by krober10nd** [comment]
thanks Zach. The goal of this pull request is to provide a bare bones geodata class that reads a shapefile and dem and plot it and provide functionality for the future.

**Comment by krober10nd** [comment]
Ok, what remains for to finish this PR are (links to each function in the original MATLAB  impl. are provided)

1) Densify (https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/%40geodata/private/my_interpm.m) 

2) Moving average smooth coastline (https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/%40geodata/private/smooth_coastline.m)

3) Coarsen shoreline outside of `bbox` (https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/%40geodata/private/coarsen_polygon.m)

We also need a unit test of `geodata` with two or three example pseudo shorelines

**Comment by krober10nd** [comment]
I ported the collapsing routine into Python. This decimates the shoreline outside of the `bbox` which accelerates the signed distance function calculation for mesh generation. 
Geodata


Now all that remains is unit testing to complete this PR. 

For the gshhs shoreline dataset for the entire north American continent, it takes about 60 seconds to process. The slowest component is `geodata.densify`. 


```
 import time
 from pyOceanMesh import *
 
 fname = (
     "/Users/Keith/junk/pyOceanMesh/datasets/gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp"
 )
 bbox = (-74.0, -70.0, 40.0, 42.0)
 h0 = 100.0
 
 t1 = time.time()
 shp = Shoreline(shp=fname, bbox=bbox, h0=h0)
 print(time.time() - t1)
 
 shp.plot()
```

**Comment by krober10nd** [comment]
Replace `pyshp` and `netcdf` with `gdal`. This removes two dependencies for one and enables the i/o of several raster formats.

**Comment by krober10nd** [comment]
add ability to read in subdomain when reading in DEM.

**Comment by krober10nd** [comment]
@zcobell any comments here?

**Comment by krober10nd** [comment]
Ok, I added in a simple tif reader just need a test for it. Not bullet proof but it gets the ball rolling.

FromTif2
FromTif

**Comment by krober10nd** [comment]
Test is up for the tif reader.

**Pull request merged**
